# Generated by Django 5.0.14 on 2026-07-22 23:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['scheduled_for']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studenttopicselection',
            options={'ordering': ['topic__track', 'topic__order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['track', 'order', 'title']},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='completed',
            new_name='is_done',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='scheduled_at',
            new_name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.topic'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttopicselection',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='background_notes',
            field=models.TextField(blank=True, help_text='Background, prior experience, and learning goals.'),
        ),
        migrations.AlterField(
            model_name='studenttopicselection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within track.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='track',
            field=models.CharField(choices=[('stata', 'Stata'), ('r', 'R'), ('python', 'Python'), ('capstone', 'Capstone')], max_length=20),
        ),
    ]
