# Generated by Django 5.0.14 on 2026-07-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assignment_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='goal_notes',
            field=models.CharField(blank=True, help_text='What the student wants to learn.', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='python_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - New to it'), (2, '2 - Basic exposure'), (3, '3 - Comfortable'), (4, '4 - Confident'), (5, '5 - Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='r_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - New to it'), (2, '2 - Basic exposure'), (3, '3 - Comfortable'), (4, '4 - Confident'), (5, '5 - Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stata_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - New to it'), (2, '2 - Basic exposure'), (3, '3 - Comfortable'), (4, '4 - Confident'), (5, '5 - Advanced')], null=True),
        ),
    ]
