# Generated by Django 5.0.14 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
