# Generated by Django 5.0.14 on 2026-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='selections_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the teacher last notified this student that their topic picks were noted.', null=True),
        ),
    ]
